const { User } = require('../models/User');
const { generatePlayerId, isValidPlayerId, PLAYER_ID_PATTERN } = require('../utils/playerId');

/*
 * Player ID assignment and the safe backfill for accounts created before the
 * Player ID existed.
 *
 * The field itself is generated by the User schema default, so every new account
 * (password signup, Google signup and admin provisioning) receives one without
 * any of those code paths having to know about it. This service exists for the
 * two things the default cannot do on its own:
 *
 *   1. Retrying a collision. A generated ID is astronomically unlikely to be
 *      taken, but if the unique index ever rejects one, a fresh ID is generated
 *      and the insert is retried, so a duplicate is never silently accepted.
 *   2. Backfilling accounts that predate the field.
 */
const MAX_PLAYER_ID_ATTEMPTS = 5;
const BACKFILL_BATCH_SIZE = 200;

function isPlayerIdConflict(error) {
  if (!error || error.code !== 11000) {
    return false;
  }

  if (error.keyPattern && Object.prototype.hasOwnProperty.call(error.keyPattern, 'playerId')) {
    return true;
  }

  return Boolean(
    error.keyValue && Object.prototype.hasOwnProperty.call(error.keyValue, 'playerId'),
  );
}

/**
 * Creates one user document with a freshly generated, unique Player ID.
 *
 * A collision on the unique Player ID index regenerates the identifier and
 * retries. Every other error, including an email or username conflict, is
 * re-thrown untouched so the caller's own error mapping still applies.
 *
 * @param {object} document          The account fields to insert.
 * @param {object} [options]
 * @param {object} [options.session] Mongoose session, used by the transactional
 *                                   admin bootstrap.
 * @param {Function} [options.generateId] Injection seam for tests, matching the
 *                                   existing `...ForTests` conventions. Production
 *                               always uses the real secure generator.
 */
async function createUserWithPlayerId(document, options = {}) {
  const { session, generateId = generatePlayerId } = options;
  const createOptions = session ? { session } : undefined;
  let lastCollision = null;

  for (let attempt = 0; attempt < MAX_PLAYER_ID_ATTEMPTS; attempt += 1) {
    try {
      const [user] = await User.create(
        [{ ...document, playerId: generateId() }],
        createOptions,
      );
      return user;
    } catch (error) {
      if (!isPlayerIdConflict(error)) {
        throw error;
      }
      lastCollision = error;
    }
  }

  throw lastCollision;
}

/*
 * Documents that need a Player ID: none at all, or a value that is not a well
 * formed Player ID. Accounts that already have a valid one are never selected,
 * so a backfill run can never overwrite an existing identifier.
 */
function getMissingPlayerIdFilter() {
  return {
    $or: [
      { playerId: { $exists: false } },
      { playerId: null },
      { playerId: '' },
      { playerId: { $not: PLAYER_ID_PATTERN } },
    ],
  };
}

/**
 * Gives a permanent Player ID to every account that does not have one.
 *
 * The write is conditional on the account still lacking a valid Player ID, so a
 * value written by a concurrent new signup is never overwritten. Each write goes
 * through the raw driver because the schema marks the path immutable, which is
 * exactly the protection this one-off migration is allowed to bypass.
 *
 * @returns {Promise<{scanned: number, assigned: number, failed: number}>}
 */
async function backfillMissingPlayerIds(options = {}) {
  const { generateId = generatePlayerId } = options;
  let scanned = 0;
  let assigned = 0;
  let failed = 0;
  let skip = 0;

  for (;;) {
    const candidates = await User.collection
      .find(getMissingPlayerIdFilter())
      .project({ _id: 1 })
      .skip(skip)
      .limit(BACKFILL_BATCH_SIZE)
      .toArray();

    if (!candidates.length) {
      break;
    }

    for (const candidate of candidates) {
      scanned += 1;
      let assignedThisUser = false;

      for (let attempt = 0; attempt < MAX_PLAYER_ID_ATTEMPTS; attempt += 1) {
        try {
          const result = await User.collection.updateOne(
            {
              _id: candidate._id,
              ...getMissingPlayerIdFilter(),
            },
            { $set: { playerId: generateId() } },
          );

          if (result.modifiedCount === 1) {
            assigned += 1;
            assignedThisUser = true;
          }
          break;
        } catch (error) {
          if (!isPlayerIdConflict(error)) {
            failed += 1;
            break;
          }
        }
      }

      if (!assignedThisUser && failed === 0) {
        // The account gained a valid Player ID between the read and the write.
        skip += 1;
      }
    }

    if (candidates.length < BACKFILL_BATCH_SIZE) {
      break;
    }
  }

  return { scanned, assigned, failed };
}

module.exports = {
  MAX_PLAYER_ID_ATTEMPTS,
  isPlayerIdConflict,
  isValidPlayerId,
  createUserWithPlayerId,
  getMissingPlayerIdFilter,
  backfillMissingPlayerIds,
};
