const crypto = require('node:crypto');

/*
 * Arcadia Player ID.
 *
 * A permanent, public-facing identifier for an Arcadia account, in the form
 *
 *   ARC-XXXXXXXX      e.g. ARC-7K4M2P9Q
 *
 * Design rules:
 *
 *   - It is generated by the server only. No endpoint accepts one, and no client
 *     ever produces or stores it.
 *   - It is not sequential. A sequential value would let anyone walk the range
 *     and enumerate accounts, so the eight characters after the prefix come from
 *     40 bits of cryptographic randomness: about 1.1 trillion possibilities.
 *   - The alphabet omits the characters that are easy to confuse when an ID is
 *     read aloud or copied by hand: I, O, 0 and 1. It is a 32 character alphabet,
 *     which is why a single random byte maps onto it without any modulo bias.
 *   - It exposes nothing about the database. It is not the MongoDB ObjectId, it
 *     is not derived from it, and it grants no access to anything. Authorization
 *     always continues to use the authenticated account identity.
 */
const PLAYER_ID_PREFIX = 'ARC-';
const PLAYER_ID_ALPHABET = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
const PLAYER_ID_RANDOM_LENGTH = 8;
// 32 possible characters, so the low 5 bits of a byte index the alphabet exactly.
const PLAYER_ID_BODY_MASK = 0x1f;

const PLAYER_ID_PATTERN = new RegExp(
  `^${PLAYER_ID_PREFIX}[${PLAYER_ID_ALPHABET}]{${PLAYER_ID_RANDOM_LENGTH}}$`,
);

if (PLAYER_ID_ALPHABET.length !== 32) {
  throw new Error('Arcadia Player ID alphabet must contain exactly 32 characters');
}

/**
 * Generates a Player ID from cryptographically secure randomness.
 *
 * Each character is taken from a fresh random byte masked to 5 bits, which is
 * an exact fit for the 32 character alphabet, so every character is uniformly
 * distributed with no bias and no rejection loop.
 */
function generatePlayerId() {
  const bytes = crypto.randomBytes(PLAYER_ID_RANDOM_LENGTH);
  let body = '';

  for (let index = 0; index < PLAYER_ID_RANDOM_LENGTH; index += 1) {
    body += PLAYER_ID_ALPHABET[bytes[index] & PLAYER_ID_BODY_MASK];
  }

  return `${PLAYER_ID_PREFIX}${body}`;
}

/** True when the value is a well formed Arcadia Player ID. */
function isValidPlayerId(value) {
  return typeof value === 'string' && PLAYER_ID_PATTERN.test(value);
}

module.exports = {
  PLAYER_ID_PREFIX,
  PLAYER_ID_ALPHABET,
  PLAYER_ID_RANDOM_LENGTH,
  PLAYER_ID_PATTERN,
  generatePlayerId,
  isValidPlayerId,
};
